# Task 5 Requirement: Run on specific port
server.port=33400

# Kafka Topic Configuration (Required for your Listener)
general.kafka-topic=trader-updates

# Database Configuration (H2)
spring.datasource.url=jdbc:h2:mem:midas
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true